# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='meassure timestamp')),
                ('temperatura', models.FloatField(blank=True, default=None, null=True)),
                ('humedad_tierra', models.FloatField(blank=True, default=None, null=True)),
                ('humedad_relativa', models.FloatField(blank=True, default=None, null=True)),
                ('luz', models.FloatField(blank=True, default=None, null=True)),
                ('distancia', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='medida',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PWSServer.Planta'),
        ),
    ]
