# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PWSServer', '0003_auto_20160817_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medida',
            old_name='planta',
            new_name='celda',
        ),
    ]
