# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PWSServer', '0004_auto_20160817_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T', 'temperatura'), ('R', 'humedad_relativa'), ('H', 'humedad_tierra'), ('L', 'luz'), ('D', 'distancia')], max_length=1)),
                ('tipo_umbral', models.CharField(choices=[('MAX', 'Maximo'), ('MIN', 'Minimo')], max_length=3)),
                ('valor', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmaTemporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_minutos', models.FloatField(blank=True, default=0.0, null=True)),
                ('alarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PWSServer.Alarma')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='celda',
            name='especie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PWSServer.Especie'),
        ),
    ]
