# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PWSServer', '0005_auto_20160817_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmaCelda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PWSServer.Alarma')),
                ('celda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PWSServer.Celda')),
            ],
        ),
        migrations.CreateModel(
            name='Suscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PWSServer.AlarmaCelda')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='suscribe',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PWSServer.Usuario'),
        ),
    ]
