# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PWSServer', '0006_auto_20160817_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T', 'temperatura'), ('R', 'humedad_relativa'), ('H', 'humedad_tierra'), ('L', 'luz'), ('D', 'distancia')], max_length=1)),
                ('tipo_umbral', models.CharField(choices=[('MAX', 'Maximo'), ('MIN', 'Minimo'), ('MED', 'Media')], max_length=3)),
                ('valor', models.FloatField(blank=True, default=0.0, null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PWSServer.Especie')),
            ],
        ),
        migrations.AlterField(
            model_name='alarma',
            name='tipo_umbral',
            field=models.CharField(choices=[('MAX', 'Maximo'), ('MIN', 'Minimo'), ('MED', 'Media')], max_length=3),
        ),
    ]
