# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWSServer', '0008_arduino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduino',
            name='identificador',
            field=models.CharField(max_length=50),
        ),
    ]
