# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PWSServer', '0010_auto_20160821_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PWSServer.Especie'),
        ),
    ]
